FROM public.ecr.aws/amazonlinux/amazonlinux:2023 AS builder
WORKDIR /build

# Install Rust and build tools
RUN yum install -y gcc openssl-devel tar gzip && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

ENV PATH="/root/.cargo/bin:${PATH}"

COPY . .
RUN ./.ci/common/scripts/install-bpf-linker.sh
RUN cargo build --release --features open-metrics

FROM public.ecr.aws/amazonlinux/amazonlinux:2023-minimal
RUN microdnf install -y util-linux iproute ethtool procps-ng && microdnf clean all
COPY --from=builder /build/target/release/network-flow-monitor-agent /usr/local/bin/nfm-agent
RUN chmod +x /usr/local/bin/nfm-agent
COPY ./charts/amazon-network-flow-monitor-agent/bin/entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/bin/sh", "/usr/local/bin/entrypoint.sh"]
