[package]
name = "nfm-controller"
description = "network-flow-monitor-agent collects networking performance statistics from the local machine"
version = "1.1.8"
edition = "2021"
build = "build.rs"
license = "Apache-2.0"
repository = "https://github.com/aws/network-flow-monitor-agent"

[[bin]]
# The controller and BPF packages join forces into a single 'network-flow-monitor-agent' executable.
name = "network-flow-monitor-agent"
path = "src/main.rs"

[lib]
name = "nfm_agent"
path = "src/lib.rs"
crate-type = ["lib"]

[features]
default = []
privileged = [] # To identify test that need privileges to run.
requires-conntrack = [
] # To identify tests that requires conntrack CLI to be present
dhat = ["dep:dhat"] # enable dhat only when requested
open-metrics = [
    "default",
    "dep:hyper",
    "dep:hyper-util",
    "dep:prometheus",
    "dep:tokio-util",
    "dep:getifaddrs",
    "dep:regex",
    "dep:tonic",
    "dep:tonic-prost",
    "dep:tower",
    "dep:tokio-stream",
]

[profile.dev]
panic = "abort"
overflow-checks = true

[dependencies]
aws-config = { version = "1.5", features = ["rustls"] }
rustls = { version = "0.23.29", default-features = false }
aws-credential-types = "1.2"
aws-sign-v4 = "0.3"
nfm-common = { version = "0.1.0", path = "../nfm-common", features = ["user"] }

# Memory profiling
dhat = { version = "0.3", optional = true }

anyhow = "1"
assert_approx_eq = "1"
hex = "0.4"
aya = "0.13"
aya-obj = "0.2"
caps = "0.5.5"
chrono = "0.4"
clap = { version = "4.1", features = ["derive"] }
criterion = "0.5"
env_logger = "0.10"
flate2 = "1.0"
futures = "0.3"
hashbrown = "0.15"
k8s-openapi = { version = "0.24", features = ["latest"] }
kube = { version = "0.99", features = [
    "runtime",
    "derive",
    "rustls-tls",
], default-features = false }
libc = "0.2"
log = "0.4"
lru = "0.18.2"
netlink-packet-core = { version = "0.7" }
netlink-packet-netfilter = { package = "reyzell-netlink-packet-netfilter", version = "0.2" }
netlink-packet-utils = { version = "0.5" }
netlink-sys = { version = "0.8" }
opentelemetry-proto = { version = "0.32", features = [
    "metrics",
    "gen-tonic-messages",
    "gen-tonic",
    "with-serde",
] }
tonic = { version = "0.14", optional = true }
tonic-prost = { version = "0.14", optional = true }
tower = { version = "0.5", optional = true }
tokio-stream = { version = "0.1", optional = true }
procfs = "0.16"
prost = "0.14"
rand = "0.8"
reqwest = { version = "0.12", features = [
    "blocking",
    "rustls-tls-native-roots",
], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shadow-rs = "1.1.0"
signal-hook = "0.3"
snap = "1.1"
structured-logger = "1.0"
sys-info = "0.9"
tokio = { version = "1.45.1", features = [
    "fs",
    "macros",
    "rt",
    "rt-multi-thread",
    "net",
    "signal",
] }
url = "2.5"
hyper = { version = "1.0", features = ["server", "http1"], optional = true }
hyper-util = { version = "0.1", features = ["tokio"], optional = true }
prometheus = { version = "0.14", optional = true }
once_cell = { version = "1.19", optional = true }
tokio-util = { version = "0.7", optional = true }
getifaddrs = { version = "0.5.0", optional = true }
regex = { version = "1.11", optional = true }

[dev-dependencies]
tempfile = "3"

[build-dependencies]
cargo_metadata = "0.19"
shadow-rs = "1.1.0"
which = { version = "6.0.0", default-features = false }
